version: '3.8'

services:
  app:
    image: atuldubey017/optimumerp
    container_name: optimumerp
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - MONGO_URI=your-mongodb-uri
      - SESSION_SECRET=YOUR_SESSION_SECRET
      - NODE_MAILER_USER_NAME=your-email@gmail.com
      - NODE_MAILER_APP_PASSWORD=your-app-password
      - NODE_MAILER_HOST=smtp.gmail.com
      - GOOGLE_AUTH_CLIENT_ID=your-google-client-id
      - GOOGLE_AUTH_CLIENT_SECRET=your-google-client-secret
      - VITE_APP_URL=http://localhost:5173
      - PDF_SHIFT_API_KEY=your-pdfshift-api-key
      - CLOUDINARY_NAME=your-cloudinary-name
      - CLOUDINARY_API_KEY=your-cloudinary-api-key
      - CLOUDINARY_API_SECRET=your-cloudinary-api-secret
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
